import { NestExpressApplication } from '@nestjs/platform-express';
import { Test } from '@nestjs/testing';
import { Pool } from 'pg';
import { AppModule } from '../../src/app.module';
import { PG_POOL } from '../../src/database/database.module';
import { InvoiceJobsService } from '../../src/invoice-jobs/invoice-jobs.service';

describe('Daily invoice jobs (legacy behavior pinned)', () => {
  let app: NestExpressApplication;
  let pool: Pool;
  let nestJobs: InvoiceJobsService;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let dbHelper: any;

  const seedOwner = async (label: string) => {
    return dbHelper.seedUser(
      `invoice-jobs-${label}-${Date.now()}-${Math.random()}@test.itemize`,
      `Invoice Jobs ${label}`,
    );
  };

  const seedOverdueInvoice = async (organizationId: number, suffix: string) => {
    const row = (
      await pool.query<{ id: number }>(
        `INSERT INTO invoices (
           organization_id, invoice_number, customer_name, status,
           due_date, subtotal, total, amount_due
         ) VALUES ($1, $2, 'Late Customer', 'sent',
                   CURRENT_DATE - INTERVAL '5 days', 100, 100, 100)
         RETURNING id`,
        [organizationId, `LATE-${suffix}-${Date.now()}`],
      )
    ).rows[0];
    return row.id;
  };

  const seedRecurringTemplate = async (
    organizationId: number,
    createdBy: number,
    suffix: string,
    overrides: { frequency?: string; endDate?: string | null } = {},
  ) => {
    const row = (
      await pool.query<{ id: number }>(
        `INSERT INTO recurring_invoice_templates (
           organization_id, template_name, customer_name, customer_email,
           frequency, start_date, end_date, next_run_date, status, items,
           subtotal, tax_amount, discount_amount, discount_value, total,
           notes, payment_terms, created_by
         ) VALUES ($1, $2, 'Recurring Customer', 'recurring@example.test',
                   $3, CURRENT_DATE - INTERVAL '60 days', $4, CURRENT_DATE,
                   'active', $5::jsonb, 200, 20, 0, 0, 220,
                   'Generated by parity spec', '14', $6)
         RETURNING id`,
        [
          organizationId,
          `Template ${suffix}`,
          overrides.frequency || 'monthly',
          overrides.endDate === undefined ? null : overrides.endDate,
          JSON.stringify([
            { name: 'Retainer', quantity: 2, unit_price: 100, tax_rate: 10 },
          ]),
          createdBy,
        ],
      )
    ).rows[0];
    return row.id;
  };

  const seedExpiredEstimate = async (
    organizationId: number,
    suffix: string,
  ) => {
    const row = (
      await pool.query<{ id: number }>(
        `INSERT INTO estimates (
           organization_id, estimate_number, customer_name, status,
           valid_until, subtotal, total
         ) VALUES ($1, $2, 'Slow Customer', 'sent',
                   CURRENT_DATE - INTERVAL '2 days', 50, 50)
         RETURNING id`,
        [organizationId, `EST-EXP-${suffix}-${Date.now()}`],
      )
    ).rows[0];
    return row.id;
  };

  beforeAll(async () => {
    if (!process.env.TEST_DATABASE_URL) {
      throw new Error('TEST_DATABASE_URL is required for invoice job tests');
    }
    process.env.JWT_SECRET ||= 'docker-integration-test-secret';
    process.env.DATABASE_URL ||= 'postgresql://unused/test';

    /* eslint-disable @typescript-eslint/no-var-requires */
    const TestDbHelper = require('../../../db/test-support/test-db-helper');
    /* eslint-enable @typescript-eslint/no-var-requires */
    dbHelper = new TestDbHelper();
    await dbHelper.setup();
    pool = dbHelper.pool;

    const moduleRef = await Test.createTestingModule({ imports: [AppModule] })
      .overrideProvider(PG_POOL)
      .useValue(pool)
      .compile();
    app = moduleRef.createNestApplication<NestExpressApplication>({
      bodyParser: false,
      logger: false,
    });
    await app.init();
    nestJobs = app.get(InvoiceJobsService);
  }, 60000);

  afterAll(async () => {
    if (app) await app.close();
    if (dbHelper) {
      const TestDbHelper = require('../../../db/test-support/test-db-helper');
      const cleanup = new TestDbHelper();
      await cleanup.setup();
      cleanup._userIds = dbHelper._userIds;
      cleanup._orgIds = dbHelper._orgIds;
      await cleanup.teardown();
    }
  }, 60000);

  it('marks past-due invoices overdue identically', async () => {
    const outcomes: Array<{ status: string }> = [];
    for (const runner of ['nest']) {
      const owner = await seedOwner(`overdue-${runner}`);
      const invoiceId = await seedOverdueInvoice(owner.org.id, runner);
      const rows = await nestJobs.runOverdueDetection();
      expect(
        rows.some((row: { id: number }) => Number(row.id) === invoiceId),
      ).toBe(true);
      const invoice = await pool.query<{ status: string }>(
        'SELECT status FROM invoices WHERE id = $1',
        [invoiceId],
      );
      outcomes.push(invoice.rows[0]);
    }
    expect(outcomes[0].status).toBe('overdue');
  });

  it('generates recurring invoices identically with items, numbering, and advance', async () => {
    const outcomes: Array<{
      invoice: Record<string, unknown>;
      items: Array<Record<string, unknown>>;
      template: Record<string, unknown>;
      invoiceNumber: string;
    }> = [];
    for (const runner of ['nest']) {
      const owner = await seedOwner(`recurring-${runner}`);
      const templateId = await seedRecurringTemplate(
        owner.org.id,
        owner.user.id,
        runner,
      );
      const generated = await nestJobs.runRecurringInvoiceGeneration();
      const entry = generated.find(
        (row: { template_id: number }) =>
          Number(row.template_id) === templateId,
      );
      expect(entry).toBeDefined();

      const invoice = (
        await pool.query(
          `SELECT customer_name, customer_email, subtotal, tax_amount, total,
                  amount_due, status, notes, recurring_template_id
           FROM invoices WHERE id = $1`,
          [entry!.invoice_id],
        )
      ).rows[0];
      const items = (
        await pool.query(
          `SELECT name, quantity, unit_price, tax_rate, tax_amount, total, sort_order
           FROM invoice_items WHERE invoice_id = $1 ORDER BY sort_order`,
          [entry!.invoice_id],
        )
      ).rows;
      const template = (
        await pool.query(
          `SELECT status, next_run_date::text AS next_run_date,
                  (last_generated_at IS NOT NULL) AS generated
           FROM recurring_invoice_templates WHERE id = $1`,
          [templateId],
        )
      ).rows[0];
      outcomes.push({
        invoice: { ...invoice, recurring_template_id: 'normalized' },
        items,
        template,
        invoiceNumber: entry!.invoice_number,
      });
    }

    const [nest] = outcomes;
    expect(nest.invoiceNumber).toMatch(/^INV-\d{5}$/);
    expect(nest.template.status).toBe('active');
    expect(nest.items).toHaveLength(1);
    expect(Number(nest.items[0].total)).toBeCloseTo(220);
  });

  it('skips recurring templates without paid entitlement identically', async () => {
    for (const runner of ['nest']) {
      const owner = await seedOwner(`unpaid-${runner}`);
      await pool.query(
        `UPDATE organizations SET subscription_status = 'none', trial_ends_at = NULL
         WHERE id = $1`,
        [owner.org.id],
      );
      const templateId = await seedRecurringTemplate(
        owner.org.id,
        owner.user.id,
        `unpaid-${runner}`,
      );
      const generated = await nestJobs.runRecurringInvoiceGeneration();
      expect(
        generated.some(
          (row: { template_id: number }) =>
            Number(row.template_id) === templateId,
        ),
      ).toBe(false);
      const template = await pool.query<{ last_generated_at: Date | null }>(
        'SELECT last_generated_at FROM recurring_invoice_templates WHERE id = $1',
        [templateId],
      );
      expect(template.rows[0].last_generated_at).toBeNull();
    }
  });

  it('completes templates whose next run passes the end date identically', async () => {
    const outcomes: Array<{ status: string; next_run_date: string }> = [];
    for (const runner of ['nest']) {
      const owner = await seedOwner(`complete-${runner}`);
      const endDate = new Date();
      endDate.setDate(endDate.getDate() + 3);
      const templateId = await seedRecurringTemplate(
        owner.org.id,
        owner.user.id,
        `complete-${runner}`,
        { frequency: 'monthly', endDate: endDate.toISOString().split('T')[0] },
      );
      const generated = await nestJobs.runRecurringInvoiceGeneration();
      expect(
        generated.some(
          (row: { template_id: number }) =>
            Number(row.template_id) === templateId,
        ),
      ).toBe(true);
      const template = (
        await pool.query<{ status: string; next_run_date: string }>(
          `SELECT status, next_run_date::text AS next_run_date
           FROM recurring_invoice_templates WHERE id = $1`,
          [templateId],
        )
      ).rows[0];
      outcomes.push(template);
    }
    const [nest] = outcomes;
    expect(nest.status).toBe('completed');
  });

  it('expires stale estimates identically', async () => {
    const outcomes: Array<{ status: string }> = [];
    for (const runner of ['nest']) {
      const owner = await seedOwner(`estimate-${runner}`);
      const estimateId = await seedExpiredEstimate(owner.org.id, runner);
      const rows = await nestJobs.runEstimateExpiryCheck();
      expect(
        rows.some((row: { id: number }) => Number(row.id) === estimateId),
      ).toBe(true);
      const estimate = await pool.query<{ status: string }>(
        'SELECT status FROM estimates WHERE id = $1',
        [estimateId],
      );
      outcomes.push(estimate.rows[0]);
    }
    expect(outcomes[0].status).toBe('expired');
  });
});
