import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { cancelSignatureDocumentViaGraphql,createSignatureDocumentViaGraphql,getSignatureDocumentViaGraphql,getSignatureEmailPreviewViaGraphql,getSignatureTemplateViaGraphql,listSignatureDocumentsViaGraphql,listSignatureTemplatesViaGraphql,updateSignatureTemplateViaGraphql } from './signaturesGraphql';
import { isSignatureCancellationGraphqlEnabled,isSignatureDocumentGraphqlMutationsEnabled,isSignatureDocumentGraphqlReadsEnabled,isSignatureEmailPreviewGraphqlEnabled,isSignatureTemplateGraphqlMutationsEnabled,isSignatureTemplateGraphqlReadsEnabled } from './graphqlClient';

vi.mock('@/lib/api',()=>({fetchCsrfToken:vi.fn(),getApiUrl:vi.fn(()=> 'https://api.itemize.test'),refreshAuthenticatedSession:vi.fn()}));
const response=(payload:unknown)=>({ok:true,status:200,json:vi.fn().mockResolvedValue(payload)}) as unknown as Response;
const document={id:7,organizationId:3,title:'NDA',documentNumber:null,description:null,message:null,status:'DRAFT',recipientCount:1,routingMode:'parallel',templateId:null,expirationDays:30,expiresAt:null,senderName:null,senderEmail:null,createdById:4,sentAt:null,completedAt:null,hasFile:true,hasSignedFile:false,fileName:'nda.pdf',fileType:'application/pdf',fileSize:1200,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-02T00:00:00Z'};
const template={id:5,organizationId:3,title:'Agreement',description:null,message:null,hasFile:true,fileName:'agreement.pdf',fileType:'application/pdf',fileSize:800,createdById:4,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-02T00:00:00Z'};
describe('signature GraphQL read consumers',()=>{
  beforeEach(()=>{vi.stubEnv('VITE_GRAPHQL_URL','https://graphql.itemize.test/graphql');vi.stubGlobal('fetch',vi.fn());});afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
  it('keeps document and template switches independent',()=>{vi.stubEnv('VITE_SIGNATURE_DOCUMENT_READS_GRAPHQL','true');vi.stubEnv('VITE_SIGNATURE_TEMPLATE_READS_GRAPHQL','false');expect(isSignatureDocumentGraphqlReadsEnabled()).toBe(true);expect(isSignatureTemplateGraphqlReadsEnabled()).toBe(false);});
  it('keeps mutation rollback switches independent',()=>{vi.stubEnv('VITE_SIGNATURE_DOCUMENT_MUTATIONS_GRAPHQL','true');vi.stubEnv('VITE_SIGNATURE_TEMPLATE_MUTATIONS_GRAPHQL','false');expect(isSignatureDocumentGraphqlMutationsEnabled()).toBe(true);expect(isSignatureTemplateGraphqlMutationsEnabled()).toBe(false);});
  it('keeps cancellation and preview rollback switches independent',()=>{vi.stubEnv('VITE_SIGNATURE_CANCELLATION_GRAPHQL','true');vi.stubEnv('VITE_SIGNATURE_EMAIL_PREVIEW_GRAPHQL','false');expect(isSignatureCancellationGraphqlEnabled()).toBe(true);expect(isSignatureEmailPreviewGraphqlEnabled()).toBe(false);});
  it('maps document paging and safe retained HTTP file URLs',async()=>{vi.mocked(fetch).mockResolvedValue(response({data:{signatureDocuments:{nodes:[document],pageInfo:{page:1,pageSize:20,total:1,totalPages:1,hasNextPage:false,hasPreviousPage:false}}}}));await expect(listSignatureDocumentsViaGraphql({status:'draft'},3)).resolves.toEqual({items:[expect.objectContaining({id:7,status:'draft',file_url:'https://api.itemize.test/api/signatures/documents/7/file'})],pagination:{page:1,limit:20,total:1,totalPages:1}});const request=JSON.parse(String((vi.mocked(fetch).mock.calls[0][1] as RequestInit).body));expect(request.variables).toEqual({filter:{status:'DRAFT'},page:{page:1,pageSize:20}});expect((vi.mocked(fetch).mock.calls[0][1] as RequestInit).headers).toMatchObject({'x-organization-id':'3'});});
  it('maps aggregate document detail without token, IP, user-agent, or hashes',async()=>{vi.mocked(fetch).mockResolvedValue(response({data:{signatureDocument:{document,recipients:[],fields:[],audit:[{id:2,documentId:7,recipientId:null,eventType:'created',description:null,createdAt:'2026-01-01T00:00:00Z'}]}}}));const result=await getSignatureDocumentViaGraphql(7,3);expect(result.document).not.toHaveProperty('original_sha256');expect(result.audit[0]).toEqual({id:2,document_id:7,event_type:'created',created_at:'2026-01-01T00:00:00Z'});});
  it('maps template list/detail and uses authenticated file streams',async()=>{vi.mocked(fetch).mockResolvedValueOnce(response({data:{signatureTemplates:[template]}})).mockResolvedValueOnce(response({data:{signatureTemplate:{template,roles:[{id:1,templateId:5,roleName:'Signer',signingOrder:1}],fields:[]}}}));await expect(listSignatureTemplatesViaGraphql(3)).resolves.toEqual([expect.objectContaining({file_url:'https://api.itemize.test/api/signatures/templates/5/file'})]);await expect(getSignatureTemplateViaGraphql(5,3)).resolves.toEqual({template:expect.objectContaining({id:5}),roles:[{id:1,template_id:5,role_name:'Signer',signing_order:1}],fields:[]});});
  it('maps document mutation aggregates to strict GraphQL inputs',async()=>{vi.mocked(fetch).mockResolvedValue(response({data:{createSignatureDocument:document}}));await expect(createSignatureDocumentViaGraphql({title:'NDA',routing_mode:'sequential'},3)).resolves.toMatchObject({id:7,status:'draft'});const request=JSON.parse(String((vi.mocked(fetch).mock.calls[0][1] as RequestInit).body));expect(request.query).toContain('mutation CreateSignatureDocument');expect(request.variables).toEqual({input:{title:'NDA',routingMode:'sequential'}});});
  it('maps template roles and fields without transport-only identifiers',async()=>{vi.mocked(fetch).mockResolvedValue(response({data:{updateSignatureTemplate:template}}));await updateSignatureTemplateViaGraphql(5,{title:'Agreement',roles:[{id:9,template_id:5,role_name:'Signer',signing_order:1}],fields:[{id:10,template_id:5,role_name:'Signer',field_type:'signature',page_number:1,x_position:10,y_position:20,width:30,height:10}]},3);const request=JSON.parse(String((vi.mocked(fetch).mock.calls[0][1] as RequestInit).body));expect(request.variables).toEqual({id:5,input:{title:'Agreement',roles:[{roleName:'Signer',signingOrder:1}],fields:[expect.objectContaining({roleName:'Signer',fieldType:'signature'})]}});});
  it('maps cancellation and strips the browser-controlled preview base URL',async()=>{vi.mocked(fetch).mockResolvedValueOnce(response({data:{cancelSignatureDocument:{...document,status:'CANCELLED'}}})).mockResolvedValueOnce(response({data:{previewSignatureEmail:{html:'<p>safe</p>',subject:'Signer'}}}));await expect(cancelSignatureDocumentViaGraphql(7,3)).resolves.toMatchObject({status:'cancelled'});await expect(getSignatureEmailPreviewViaGraphql({message:'Sign',senderName:'A',baseUrl:'https://attacker.test'},3)).resolves.toEqual({html:'<p>safe</p>',subject:'Signer'});const previewRequest=JSON.parse(String((vi.mocked(fetch).mock.calls[1][1] as RequestInit).body));expect(previewRequest.query).toContain('query SignatureEmailPreview');expect(previewRequest.variables).toEqual({input:{message:'Sign',senderName:'A'}});});
});
