import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { getSignatureDocumentViaGraphql,getSignatureTemplateViaGraphql,listSignatureDocumentsViaGraphql,listSignatureTemplatesViaGraphql } from './signaturesGraphql';
import { isSignatureDocumentGraphqlReadsEnabled,isSignatureTemplateGraphqlReadsEnabled } from './graphqlClient';

vi.mock('@/lib/api',()=>({fetchCsrfToken:vi.fn(),getApiUrl:vi.fn(()=> 'https://api.itemize.test'),refreshAuthenticatedSession:vi.fn()}));
const response=(payload:unknown)=>({ok:true,status:200,json:vi.fn().mockResolvedValue(payload)}) as unknown as Response;
const document={id:7,organizationId:3,title:'NDA',documentNumber:null,description:null,message:null,status:'DRAFT',recipientCount:1,routingMode:'parallel',templateId:null,expirationDays:30,expiresAt:null,senderName:null,senderEmail:null,createdById:4,sentAt:null,completedAt:null,hasFile:true,hasSignedFile:false,fileName:'nda.pdf',fileType:'application/pdf',fileSize:1200,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-02T00:00:00Z'};
const template={id:5,organizationId:3,title:'Agreement',description:null,message:null,hasFile:true,fileName:'agreement.pdf',fileType:'application/pdf',fileSize:800,createdById:4,createdAt:'2026-01-01T00:00:00Z',updatedAt:'2026-01-02T00:00:00Z'};
describe('signature GraphQL read consumers',()=>{
  beforeEach(()=>{vi.stubEnv('VITE_GRAPHQL_URL','https://graphql.itemize.test/graphql');vi.stubGlobal('fetch',vi.fn());});afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();});
  it('keeps document and template switches independent',()=>{vi.stubEnv('VITE_SIGNATURE_DOCUMENT_READS_GRAPHQL','true');vi.stubEnv('VITE_SIGNATURE_TEMPLATE_READS_GRAPHQL','false');expect(isSignatureDocumentGraphqlReadsEnabled()).toBe(true);expect(isSignatureTemplateGraphqlReadsEnabled()).toBe(false);});
  it('maps document paging and safe retained HTTP file URLs',async()=>{vi.mocked(fetch).mockResolvedValue(response({data:{signatureDocuments:{nodes:[document],pageInfo:{page:1,pageSize:20,total:1,totalPages:1,hasNextPage:false,hasPreviousPage:false}}}}));await expect(listSignatureDocumentsViaGraphql({status:'draft'},3)).resolves.toEqual({items:[expect.objectContaining({id:7,status:'draft',file_url:'https://api.itemize.test/api/signatures/documents/7/file'})],pagination:{page:1,limit:20,total:1,totalPages:1}});const request=JSON.parse(String((vi.mocked(fetch).mock.calls[0][1] as RequestInit).body));expect(request.variables).toEqual({filter:{status:'DRAFT'},page:{page:1,pageSize:20}});expect((vi.mocked(fetch).mock.calls[0][1] as RequestInit).headers).toMatchObject({'x-organization-id':'3'});});
  it('maps aggregate document detail without token, IP, user-agent, or hashes',async()=>{vi.mocked(fetch).mockResolvedValue(response({data:{signatureDocument:{document,recipients:[],fields:[],audit:[{id:2,documentId:7,recipientId:null,eventType:'created',description:null,createdAt:'2026-01-01T00:00:00Z'}]}}}));const result=await getSignatureDocumentViaGraphql(7,3);expect(result.document).not.toHaveProperty('original_sha256');expect(result.audit[0]).toEqual({id:2,document_id:7,event_type:'created',created_at:'2026-01-01T00:00:00Z'});});
  it('maps template list/detail and uses authenticated file streams',async()=>{vi.mocked(fetch).mockResolvedValueOnce(response({data:{signatureTemplates:[template]}})).mockResolvedValueOnce(response({data:{signatureTemplate:{template,roles:[{id:1,templateId:5,roleName:'Signer',signingOrder:1}],fields:[]}}}));await expect(listSignatureTemplatesViaGraphql(3)).resolves.toEqual([expect.objectContaining({file_url:'https://api.itemize.test/api/signatures/templates/5/file'})]);await expect(getSignatureTemplateViaGraphql(5,3)).resolves.toEqual({template:expect.objectContaining({id:5}),roles:[{id:1,template_id:5,role_name:'Signer',signing_order:1}],fields:[]});});
});
