/**
 * Backward compatibility with artifacts the retired Express runtime
 * produced: OAuth states (URLs in flight) and token envelopes (rows at
 * rest). The envelope fixtures below were generated by the legacy
 * implementation (backend/src/utils/calendarTokenEncryption.js) before
 * its retirement, under the same derived test key this suite
 * configures — decrypting them proves historical at-rest tokens stay
 * readable. States carry a 10-minute TTL so legacy-minted fixtures
 * cannot be pinned; their format compatibility was proven by the
 * dual-runtime suite before retirement, and the round-trip, expiry,
 * and tamper properties remain covered here.
 */
import {
  createCalendarOAuthState,
  normalizeReturnPath,
  verifyCalendarOAuthState,
} from './calendar-oauth-state';
import {
  calendarTokenNeedsRotation,
  decryptCalendarToken,
  encryptCalendarToken,
} from './calendar-token-encryption';

// Generated by the legacy runtime with JWT_SECRET='calendar-compat-secret'.
const LEGACY_ACCESS_ENVELOPE =
  'enc:v1:dev-derived-v1:TkAenMWPlUXTNk56:ADOOxeRbA4JihCPdw8WThrY:FSqmJpcbEZyEwEjrsXhCOQ';
const LEGACY_REFRESH_ENVELOPE =
  'enc:v1:dev-derived-v1:Qk78KCyiN53_QRPr:UweP7S-CyWvUMmA5RhIhlg:Fh3wLtVf6FFPd3uLj8ZchQ';
// Generated by the legacy runtime under the explicit k1 keyring below.
const LEGACY_K1_ENVELOPE =
  'enc:v1:k1:IF9YFrfeNrW-QWti:9e86tj_Kw6_YOPp1L40:gZayvib6WRcjg3ozh2VWKw';

describe('calendar OAuth legacy-artifact compatibility', () => {
  const savedEnv = { ...process.env };

  beforeEach(() => {
    process.env.JWT_SECRET = 'calendar-compat-secret';
    delete process.env.CALENDAR_OAUTH_STATE_SECRET;
    delete process.env.CALENDAR_TOKEN_ENCRYPTION_KEYS;
    delete process.env.CALENDAR_TOKEN_ACTIVE_KEY_ID;
  });

  afterAll(() => {
    for (const name of [
      'JWT_SECRET',
      'CALENDAR_OAUTH_STATE_SECRET',
      'CALENDAR_TOKEN_ENCRYPTION_KEYS',
      'CALENDAR_TOKEN_ACTIVE_KEY_ID',
    ]) {
      if (savedEnv[name] === undefined) delete process.env[name];
      else process.env[name] = savedEnv[name];
    }
  });

  it('round-trips states and preserves the verified projection', () => {
    const values = { userId: 7, organizationId: 3, returnUrl: '/calendars?tab=sync' };
    const state = createCalendarOAuthState(values);
    expect(verifyCalendarOAuthState(state)).toEqual({
      userId: 7,
      organizationId: 3,
      returnPath: '/calendars?tab=sync',
    });
  });

  it('rejects expired and tampered states', () => {
    const stale = createCalendarOAuthState(
      { userId: 7, organizationId: 3 },
      { now: Date.now() - 11 * 60 * 1000 },
    );
    expect(() => verifyCalendarOAuthState(stale)).toThrow(
      'Expired or invalid OAuth state',
    );

    const tampered = `${createCalendarOAuthState({ userId: 7, organizationId: 3 }).split('.')[0]}.AAAA`;
    expect(() => verifyCalendarOAuthState(tampered)).toThrow(
      'Invalid OAuth state signature',
    );
  });

  it('normalizes return paths to safe app-relative values', () => {
    expect(normalizeReturnPath('/calendars?ok=1')).toBe('/calendars?ok=1');
    for (const value of [
      'https://evil.example.com',
      '//evil.example.com',
      '/pa\\th',
      '/line\nbreak',
      42,
    ]) {
      expect(normalizeReturnPath(value)).toBe('/calendars');
    }
  });

  it('decrypts envelopes the legacy runtime produced', () => {
    expect(decryptCalendarToken(LEGACY_ACCESS_ENVELOPE, 'access')).toBe(
      'ya29.access-token',
    );
    expect(decryptCalendarToken(LEGACY_REFRESH_ENVELOPE, 'refresh')).toBe(
      '1//refresh-token',
    );
  });

  it('binds envelopes to their token type', () => {
    expect(() =>
      decryptCalendarToken(LEGACY_ACCESS_ENVELOPE, 'refresh'),
    ).toThrow('Calendar token envelope failed authentication');
    const fresh = encryptCalendarToken('ya29.new-token', 'access');
    expect(() => decryptCalendarToken(fresh, 'refresh')).toThrow(
      'Calendar token envelope failed authentication',
    );
  });

  it('flags legacy-keyed envelopes for rotation under a newer keyring', () => {
    const oldKeys = {
      CALENDAR_TOKEN_ENCRYPTION_KEYS: JSON.stringify({ k1: 'ab'.repeat(32) }),
      CALENDAR_TOKEN_ACTIVE_KEY_ID: 'k1',
    } as NodeJS.ProcessEnv;
    const newKeys = {
      CALENDAR_TOKEN_ENCRYPTION_KEYS: JSON.stringify({
        k1: 'ab'.repeat(32),
        k2: 'cd'.repeat(32),
      }),
      CALENDAR_TOKEN_ACTIVE_KEY_ID: 'k2',
    } as NodeJS.ProcessEnv;
    expect(calendarTokenNeedsRotation(LEGACY_K1_ENVELOPE, oldKeys)).toBe(false);
    expect(calendarTokenNeedsRotation(LEGACY_K1_ENVELOPE, newKeys)).toBe(true);
    expect(decryptCalendarToken(LEGACY_K1_ENVELOPE, 'access', newKeys)).toBe(
      'token-under-k1',
    );
  });
});
