import { describe, it, expect } from 'vitest';
import { env } from './env';

describe('Environment Validation', () => {
  it('accepts the Vitest runtime mode during application initialization', () => {
    expect(env).toBeDefined();
    expect(env.MODE).toBe('test');
    expect(env.VITE_CONTACT_READS_GRAPHQL).toBe('false');
    expect(env.VITE_CONTACT_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_CONTACT_BULK_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_CONTACT_ACTIVITIES_GRAPHQL).toBe('false');
    expect(env.VITE_CONTACT_CONTENT_GRAPHQL).toBe('false');
    expect(env.VITE_PIPELINE_READS_GRAPHQL).toBe('false');
    expect(env.VITE_PIPELINE_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_DEAL_READS_GRAPHQL).toBe('false');
    expect(env.VITE_DEAL_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_FORM_READS_GRAPHQL).toBe('false');
    expect(env.VITE_FORM_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_FORM_SUBMISSIONS_GRAPHQL).toBe('false');
    expect(env.VITE_ORGANIZATION_READS_GRAPHQL).toBe('false');
    expect(env.VITE_ORGANIZATION_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_CALENDAR_READS_GRAPHQL).toBe('false');
    expect(env.VITE_CALENDAR_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_CALENDAR_AVAILABILITY_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_CALENDAR_INTEGRATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_BOOKING_READS_GRAPHQL).toBe('false');
    expect(env.VITE_BOOKING_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_BOOKING_SCHEDULING_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_PRODUCT_READS_GRAPHQL).toBe('false');
    expect(env.VITE_PRODUCT_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_INVOICE_BUSINESS_READS_GRAPHQL).toBe('false');
    expect(env.VITE_INVOICE_BUSINESS_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_INVOICE_SETTINGS_READS_GRAPHQL).toBe('false');
    expect(env.VITE_INVOICE_SETTINGS_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_INVOICE_EMAIL_PREVIEW_GRAPHQL).toBe('false');
    expect(env.VITE_INVOICE_READS_GRAPHQL).toBe('false');
    expect(env.VITE_INVOICE_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_ESTIMATE_READS_GRAPHQL).toBe('false');
    expect(env.VITE_ESTIMATE_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_ESTIMATE_CONVERSION_GRAPHQL).toBe('false');
    expect(env.VITE_RECURRING_INVOICE_READS_GRAPHQL).toBe('false');
    expect(env.VITE_RECURRING_INVOICE_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_RECURRING_INVOICE_LIFECYCLE_GRAPHQL).toBe('false');
    expect(env.VITE_RECURRING_INVOICE_CLONE_GRAPHQL).toBe('false');
    expect(env.VITE_RECURRING_INVOICE_GENERATION_GRAPHQL).toBe('false');
    expect(env.VITE_PAYMENT_READS_GRAPHQL).toBe('false');
    expect(env.VITE_PAYMENT_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_WORKSPACE_LIST_READS_GRAPHQL).toBe('false');
    expect(env.VITE_WORKSPACE_LIST_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_WORKSPACE_NOTE_READS_GRAPHQL).toBe('false');
    expect(env.VITE_WORKSPACE_NOTE_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_WORKSPACE_WHITEBOARD_READS_GRAPHQL).toBe('false');
    expect(env.VITE_WORKSPACE_WHITEBOARD_MUTATIONS_GRAPHQL).toBe('false');
    expect(env.VITE_DASHBOARD_ANALYTICS_GRAPHQL).toBe('false');
    expect(env.VITE_DEV_AUTH_PROBE_WITHOUT_HINT).toBe('false');
  });
});
