const REVIEW_PLATFORM_COLUMNS = [
    'id',
    'organization_id',
    'platform',
    'platform_name',
    'place_id',
    'page_id',
    'business_url',
    'review_url',
    'access_token',
    'refresh_token',
    'token_expires_at',
    'total_reviews',
    'average_rating',
    'last_synced_at',
    'is_active',
    'is_connected',
    'created_at',
    'updated_at'
].join(', ');

const REVIEW_COLUMNS = [
    'id',
    'organization_id',
    'platform_id',
    'platform',
    'external_review_id',
    'rating',
    'review_text',
    'reviewer_name',
    'reviewer_email',
    'reviewer_phone',
    'reviewer_avatar_url',
    'reviewer_profile_url',
    'contact_id',
    'status',
    'response_text',
    'responded_at',
    'responded_by',
    'internal_notes',
    'sentiment',
    'sentiment_score',
    'source',
    'review_request_id',
    'review_date',
    'created_at',
    'updated_at'
].join(', ');

const REVIEW_REQUEST_COLUMNS = [
    'id',
    'organization_id',
    'contact_id',
    'contact_email',
    'contact_phone',
    'contact_name',
    'channel',
    'template_id',
    'email_sent',
    'email_sent_at',
    'email_opened',
    'email_opened_at',
    'sms_sent',
    'sms_sent_at',
    'clicked',
    'clicked_at',
    'rating_given',
    'review_submitted',
    'review_submitted_at',
    'review_id',
    'preferred_platform',
    'redirect_url',
    'status',
    'scheduled_at',
    'expires_at',
    'custom_message',
    'unique_token',
    'created_at',
    'updated_at'
].join(', ');

const REVIEW_WIDGET_COLUMNS = [
    'id',
    'organization_id',
    'widget_key',
    'name',
    'widget_type',
    'theme',
    'primary_color',
    'background_color',
    'text_color',
    'border_radius',
    'show_rating_stars',
    'show_reviewer_photo',
    'show_review_date',
    'show_platform_icon',
    'min_rating',
    'platforms',
    'max_reviews',
    'hide_no_text_reviews',
    'auto_refresh',
    'refresh_interval_hours',
    'is_active',
    'created_at',
    'updated_at'
].join(', ');

const REPUTATION_SETTINGS_COLUMNS = [
    'id',
    'organization_id',
    'auto_request_enabled',
    'auto_request_delay_days',
    'auto_request_channel',
    'auto_request_trigger',
    'email_template_id',
    'sms_template_text',
    'negative_threshold',
    'negative_alert_email',
    'negative_route_internal',
    'positive_route_url',
    'default_review_url',
    'google_place_id',
    'new_review_notify_email',
    'new_review_notify_slack',
    'slack_webhook_url',
    'created_at',
    'updated_at'
].join(', ');

module.exports = {
    REVIEW_PLATFORM_COLUMNS,
    REVIEW_COLUMNS,
    REVIEW_REQUEST_COLUMNS,
    REVIEW_WIDGET_COLUMNS,
    REPUTATION_SETTINGS_COLUMNS
};
