import { SignatureDocumentStatus } from './signature-document.enums';
import { SignatureDocumentsRepository } from './signature-documents.repository';
import { SignatureDocumentsService } from './signature-documents.service';

const document={id:7,organization_id:3,title:'NDA',document_number:null,description:null,message:null,status:SignatureDocumentStatus.DRAFT,recipient_count:1,routing_mode:'parallel',template_id:null,expiration_days:30,expires_at:null,sender_name:null,sender_email:null,created_by:4,sent_at:null,completed_at:null,has_file:true,has_signed_file:false,file_name:'nda.pdf',file_type:'application/pdf',file_size:'1200',created_at:new Date('2026-01-01'),updated_at:new Date('2026-01-02')};

describe('SignatureDocumentsService',()=>{
  const repository={hasFeatureAccess:jest.fn(),findPage:jest.fn(),findDetail:jest.fn(),findAudit:jest.fn(),createDraft:jest.fn(),updateDraft:jest.fn(),deleteDraft:jest.fn(),removeDraftFile:jest.fn(),cancelDocument:jest.fn()} as unknown as jest.Mocked<SignatureDocumentsRepository>;
  const service=new SignatureDocumentsService(repository);
  beforeEach(()=>{jest.clearAllMocks();repository.hasFeatureAccess.mockResolvedValue(true);});
  it('maps bounded tenant document pages without storage or evidence secrets',async()=>{repository.findPage.mockResolvedValue({rows:[document],total:1});await expect(service.list(3,{status:SignatureDocumentStatus.DRAFT},{page:1,pageSize:20})).resolves.toEqual({nodes:[expect.objectContaining({id:7,hasFile:true,fileSize:1200})],pageInfo:expect.objectContaining({total:1})});expect(repository.findPage).toHaveBeenCalledWith({organizationId:3,status:SignatureDocumentStatus.DRAFT,pageSize:20,offset:0});});
  it('maps detail children and audit while preserving private misses',async()=>{repository.findDetail.mockResolvedValue({document,recipients:[],fields:[],audit:[]});await expect(service.detail(3,7)).resolves.toEqual({document:expect.objectContaining({id:7}),recipients:[],fields:[],audit:[]});repository.findDetail.mockResolvedValue(null);await expect(service.detail(3,8)).rejects.toMatchObject({extensions:{code:'NOT_FOUND'}});});
  it('enforces feature access and page bounds before repository reads',async()=>{repository.hasFeatureAccess.mockResolvedValue(false);await expect(service.list(3)).rejects.toMatchObject({extensions:{code:'FORBIDDEN'}});repository.hasFeatureAccess.mockResolvedValue(true);await expect(service.list(3,{}, {page:0,pageSize:20})).rejects.toMatchObject({extensions:{code:'BAD_USER_INPUT'}});});
  it('normalizes a bounded atomic draft aggregate',async()=>{repository.createDraft.mockResolvedValue(document);await expect(service.create(3,4,{title:' NDA ',recipients:[{email:'SIGNER@Test.Itemize',roleName:'Signer'}],fields:[{roleName:'Signer',fieldType:'signature',pageNumber:1,xPosition:10,yPosition:20,width:30,height:10}]})).resolves.toMatchObject({id:7});expect(repository.createDraft).toHaveBeenCalledWith(3,4,expect.objectContaining({title:'NDA',expirationDays:30,routingMode:'parallel',recipients:[expect.objectContaining({email:'signer@test.itemize',identityMethod:'none'})],fields:[expect.objectContaining({fieldType:'signature',isRequired:true})]}));});
  it('rejects unsupported identity and out-of-page geometry before writes',async()=>{await expect(service.create(3,4,{title:'NDA',recipients:[{email:'signer@test.itemize',identityMethod:'email_otp'}]})).rejects.toMatchObject({extensions:{code:'BAD_USER_INPUT',reason:'UNSUPPORTED_SIGNATURE_IDENTITY_METHOD'}});await expect(service.update(3,7,{fields:[{fieldType:'text',pageNumber:1,xPosition:90,yPosition:0,width:20,height:10}]})).rejects.toMatchObject({extensions:{code:'BAD_USER_INPUT',reason:'INVALID_SIGNATURE_FIELD_GEOMETRY'}});expect(repository.createDraft).not.toHaveBeenCalled();expect(repository.updateDraft).not.toHaveBeenCalled();});
  it('maps idempotent cancellation and rejects completed documents',async()=>{repository.cancelDocument.mockResolvedValue({row:{...document,status:SignatureDocumentStatus.CANCELLED},status:'cancelled'});await expect(service.cancel(3,7)).resolves.toMatchObject({id:7,status:SignatureDocumentStatus.CANCELLED});repository.cancelDocument.mockResolvedValue({row:{...document,status:SignatureDocumentStatus.COMPLETED},status:'completed'});await expect(service.cancel(3,7)).rejects.toMatchObject({extensions:{code:'CONFLICT',reason:'SIGNATURE_DOCUMENT_COMPLETED'}});});
  it('maps draft file removal and rejects immutable lifecycle states',async()=>{repository.removeDraftFile.mockResolvedValue({row:{...document,has_file:false,file_name:null,file_size:null,file_type:null},status:'draft'});await expect(service.removeFile(3,7)).resolves.toMatchObject({id:7,hasFile:false});repository.removeDraftFile.mockResolvedValue({row:null,status:'sent'});await expect(service.removeFile(3,7)).rejects.toMatchObject({extensions:{code:'CONFLICT',reason:'SIGNATURE_DOCUMENT_NOT_DRAFT'}});});
  it('rejects deletion of immutable lifecycle states',async()=>{repository.deleteDraft.mockResolvedValue({row:null,status:'sent'});await expect(service.delete(3,7)).rejects.toMatchObject({extensions:{code:'CONFLICT',reason:'SIGNATURE_DOCUMENT_NOT_DRAFT'}});});
});
