import { Injectable } from '@nestjs/common';
import { itemizeGraphqlError } from '../common/graphql-error';
import { SignatureDocument } from '../signature-documents/signature-document.types';
import { SignatureDocumentRow, SignatureQuotaExceededError, SignatureRecipientWrite, SignatureReferenceError } from '../signature-documents/signature-documents.repository';
import { SignatureRecipientInput } from '../signature-documents/signature-document.inputs';
import { CreateSignatureTemplateInput, InstantiateSignatureTemplateInput, SignatureTemplateFieldInput, SignatureTemplateRoleInput, UpdateSignatureTemplateInput } from './signature-template.inputs';
import { SignatureTemplate, SignatureTemplateDetail, SignatureTemplateField, SignatureTemplateRole } from './signature-template.types';
import { SignatureTemplateFieldRow, SignatureTemplateFieldWrite, SignatureTemplateRoleRow, SignatureTemplateRoleWrite, SignatureTemplateRow, SignatureTemplatesRepository } from './signature-templates.repository';

const FIELD_TYPES=new Set(['signature','initials','text','date','checkbox']);
const EMAIL=/^[^\s@]+@[^\s@]+\.[^\s@]+$/;

@Injectable()
export class SignatureTemplatesService {
  constructor(private readonly repository:SignatureTemplatesRepository){}
  async list(organizationId:number):Promise<SignatureTemplate[]>{await this.access(organizationId);return (await this.repository.findAll(organizationId)).map(r=>this.template(r));}
  async detail(organizationId:number,id:number):Promise<SignatureTemplateDetail>{await this.access(organizationId);this.id(id);const r=await this.repository.findDetail(organizationId,id);if(!r)throw itemizeGraphqlError('Signature template not found','NOT_FOUND');return {template:this.template(r.template),roles:r.roles.map(x=>this.role(x)),fields:r.fields.map(x=>this.field(x))};}
  async create(organizationId:number,userId:number,input:CreateSignatureTemplateInput):Promise<SignatureTemplate>{await this.access(organizationId);const roles=input.roles===undefined?undefined:this.roles(input.roles);const fields=input.fields===undefined?undefined:this.fields(input.fields);this.fieldRoles(fields??[],roles??[]);try{return this.template(await this.repository.create(organizationId,userId,{title:this.requiredText(input.title,'title',255),description:this.optionalText(input.description,'description',10000),message:this.optionalText(input.message,'message',50000),...(roles===undefined?{}:{roles}),...(fields===undefined?{}:{fields})}));}catch(error){this.writeError(error);}}
  async update(organizationId:number,id:number,input:UpdateSignatureTemplateInput):Promise<SignatureTemplate>{await this.access(organizationId);this.id(id);if(input.title===null)throw this.bad('title cannot be null','title','NULL_SIGNATURE_TEMPLATE_TITLE');if(input.roles===null)throw this.bad('roles cannot be null','roles','NULL_SIGNATURE_TEMPLATE_ROLES');if(input.fields===null)throw this.bad('fields cannot be null','fields','NULL_SIGNATURE_TEMPLATE_FIELDS');const roles=input.roles===undefined?undefined:this.roles(input.roles as SignatureTemplateRoleInput[]);const fields=input.fields===undefined?undefined:this.fields(input.fields as SignatureTemplateFieldInput[]);if(roles!==undefined&&fields!==undefined)this.fieldRoles(fields,roles);try{const row=await this.repository.update(organizationId,id,{...(input.title===undefined?{}:{title:this.requiredText(input.title as string,'title',255)}),...(Object.prototype.hasOwnProperty.call(input,'description')?{description:this.optionalText(input.description,'description',10000)}:{}),...(Object.prototype.hasOwnProperty.call(input,'message')?{message:this.optionalText(input.message,'message',50000)}:{}),...(roles===undefined?{}:{roles}),...(fields===undefined?{}:{fields})});if(!row)throw itemizeGraphqlError('Signature template not found','NOT_FOUND');return this.template(row);}catch(error){this.writeError(error);}}
  async delete(organizationId:number,id:number):Promise<SignatureTemplate>{await this.access(organizationId);this.id(id);const row=await this.repository.delete(organizationId,id);if(!row)throw itemizeGraphqlError('Signature template not found','NOT_FOUND');return this.template(row);}
  async instantiate(organizationId:number,userId:number,id:number,input:InstantiateSignatureTemplateInput):Promise<SignatureDocument>{await this.access(organizationId);this.id(id);const recipients=this.recipients(input.recipients??[]);try{const row=await this.repository.instantiate(organizationId,userId,id,{title:Object.prototype.hasOwnProperty.call(input,'title')?this.optionalText(input.title,'title',255):null,description:Object.prototype.hasOwnProperty.call(input,'description')?this.optionalText(input.description,'description',10000):undefined,message:Object.prototype.hasOwnProperty.call(input,'message')?this.optionalText(input.message,'message',50000):undefined,routingMode:this.routing(input.routingMode??'parallel'),expirationDays:this.expiration(input.expirationDays??30),senderName:this.optionalText(input.senderName,'senderName',255),senderEmail:this.optionalEmail(input.senderEmail),recipients});if(!row)throw itemizeGraphqlError('Signature template not found','NOT_FOUND');return this.document(row);}catch(error){this.writeError(error);}}
  private async access(organizationId:number):Promise<void>{if(!(await this.repository.hasFeatureAccess(organizationId)))throw itemizeGraphqlError('E-Signatures require an upgrade.','FORBIDDEN',{reason:'FEATURE_NOT_AVAILABLE'});}
  private id(value:number):void{if(!Number.isInteger(value)||value<1)throw itemizeGraphqlError('id must be a positive integer','BAD_USER_INPUT',{field:'id'});}
  private template(r:SignatureTemplateRow):SignatureTemplate{return{id:r.id,organizationId:r.organization_id,title:r.title,description:r.description,message:r.message,hasFile:r.has_file,fileName:r.file_name,fileType:r.file_type,fileSize:r.file_size===null?null:Number(r.file_size),createdById:r.created_by,createdAt:r.created_at,updatedAt:r.updated_at};}
  private role(r:SignatureTemplateRoleRow):SignatureTemplateRole{return{id:r.id,templateId:r.template_id,roleName:r.role_name,signingOrder:r.signing_order};}
  private field(r:SignatureTemplateFieldRow):SignatureTemplateField{return{id:r.id,templateId:r.template_id,roleName:r.role_name,fieldType:r.field_type,pageNumber:r.page_number,xPosition:Number(r.x_position),yPosition:Number(r.y_position),width:Number(r.width),height:Number(r.height),label:r.label,isRequired:r.is_required,fontSize:r.font_size,fontFamily:r.font_family,textAlign:r.text_align,locked:r.locked};}
  private roles(input:SignatureTemplateRoleInput[]):SignatureTemplateRoleWrite[]{if(input.length>50)throw this.bad('At most 50 roles are allowed','roles','SIGNATURE_TEMPLATE_ROLE_LIMIT');const names=new Set<string>();return input.map((role,index)=>{const roleName=this.requiredText(role.roleName,`roles.${index}.roleName`,100);const key=roleName.toLowerCase();if(names.has(key))throw this.bad('Role names must be unique',`roles.${index}.roleName`,'DUPLICATE_SIGNATURE_TEMPLATE_ROLE');names.add(key);const signingOrder=role.signingOrder??1;if(!Number.isSafeInteger(signingOrder)||signingOrder<1)throw this.bad('signingOrder must be a positive integer',`roles.${index}.signingOrder`,'INVALID_SIGNATURE_SIGNING_ORDER');return{roleName,signingOrder};});}
  private fields(input:SignatureTemplateFieldInput[]):SignatureTemplateFieldWrite[]{if(input.length>500)throw this.bad('At most 500 fields are allowed','fields','SIGNATURE_TEMPLATE_FIELD_LIMIT');return input.map((f,index)=>{if(!FIELD_TYPES.has(f.fieldType))throw this.bad('fieldType is invalid',`fields.${index}.fieldType`,'INVALID_SIGNATURE_FIELD_TYPE');if(!Number.isSafeInteger(f.pageNumber)||f.pageNumber<1||f.pageNumber>10000)throw this.bad('pageNumber is invalid',`fields.${index}.pageNumber`,'INVALID_SIGNATURE_FIELD_PAGE');if(![f.xPosition,f.yPosition,f.width,f.height].every(Number.isFinite)||f.xPosition<0||f.yPosition<0||f.width<=0||f.height<=0||f.xPosition+f.width>100||f.yPosition+f.height>100)throw this.bad('Field geometry must fit within the page',`fields.${index}`,'INVALID_SIGNATURE_FIELD_GEOMETRY');const fontSize=f.fontSize===undefined||f.fontSize===null?null:f.fontSize;if(fontSize!==null&&(!Number.isSafeInteger(fontSize)||fontSize<1||fontSize>200))throw this.bad('fontSize is invalid',`fields.${index}.fontSize`,'INVALID_SIGNATURE_FONT_SIZE');return{roleName:this.optionalText(f.roleName,`fields.${index}.roleName`,100),fieldType:f.fieldType,pageNumber:f.pageNumber,xPosition:f.xPosition,yPosition:f.yPosition,width:f.width,height:f.height,label:this.optionalText(f.label,`fields.${index}.label`,255),isRequired:f.isRequired??true,fontSize,fontFamily:this.optionalText(f.fontFamily,`fields.${index}.fontFamily`,100),textAlign:this.optionalText(f.textAlign,`fields.${index}.textAlign`,10),locked:f.locked??false};});}
  private fieldRoles(fields:SignatureTemplateFieldWrite[],roles:SignatureTemplateRoleWrite[]):void{const names=new Set(roles.map(r=>r.roleName.toLowerCase()));for(const [index,field]of fields.entries())if(field.roleName!==null&&!names.has(field.roleName.toLowerCase()))throw this.bad('Field role must belong to the template',`fields.${index}.roleName`,'INVALID_SIGNATURE_TEMPLATE_FIELD_ROLE');}
  private recipients(input:SignatureRecipientInput[]):SignatureRecipientWrite[]{if(input.length>50)throw this.bad('At most 50 recipients are allowed','recipients','SIGNATURE_RECIPIENT_LIMIT');const emails=new Set<string>();const roles=new Set<string>();return input.map((r,index)=>{const email=String(r.email??'').trim().toLowerCase();if(email.length>255||!EMAIL.test(email))throw this.bad('Recipient email is invalid',`recipients.${index}.email`,'INVALID_SIGNATURE_RECIPIENT_EMAIL');if(emails.has(email))throw this.bad('Recipient emails must be unique',`recipients.${index}.email`,'DUPLICATE_SIGNATURE_RECIPIENT_EMAIL');emails.add(email);const roleName=this.optionalText(r.roleName,`recipients.${index}.roleName`,100);if(roleName!==null){const key=roleName.toLowerCase();if(roles.has(key))throw this.bad('Recipient roles must be unique',`recipients.${index}.roleName`,'DUPLICATE_SIGNATURE_RECIPIENT_ROLE');roles.add(key);}const signingOrder=r.signingOrder??1;if(!Number.isSafeInteger(signingOrder)||signingOrder<1)throw this.bad('signingOrder must be positive',`recipients.${index}.signingOrder`,'INVALID_SIGNATURE_SIGNING_ORDER');const identityMethod=r.identityMethod??'none';if(identityMethod!=='none')throw this.bad('Only link-based signing is currently supported',`recipients.${index}.identityMethod`,'UNSUPPORTED_SIGNATURE_IDENTITY_METHOD');return{contactId:r.contactId===undefined||r.contactId===null?null:this.positiveId(r.contactId,`recipients.${index}.contactId`),name:this.optionalText(r.name,`recipients.${index}.name`,255),email,signingOrder,roleName,identityMethod};});}
  private document(r:SignatureDocumentRow):SignatureDocument{return{id:r.id,organizationId:r.organization_id,title:r.title,documentNumber:r.document_number,description:r.description,message:r.message,status:r.status,recipientCount:Number(r.recipient_count),routingMode:r.routing_mode,templateId:r.template_id,expirationDays:r.expiration_days,expiresAt:r.expires_at,senderName:r.sender_name,senderEmail:r.sender_email,createdById:r.created_by,sentAt:r.sent_at,completedAt:r.completed_at,hasFile:r.has_file,hasSignedFile:r.has_signed_file,fileName:r.file_name,fileType:r.file_type,fileSize:r.file_size===null?null:Number(r.file_size),createdAt:r.created_at,updatedAt:r.updated_at};}
  private requiredText(value:string,field:string,max:number):string{const normalized=String(value??'').trim();if(!normalized||normalized.length>max)throw this.bad(`${field} must be between 1 and ${max} characters`,field,'INVALID_SIGNATURE_TEMPLATE_TEXT');return normalized;}
  private optionalText(value:string|null|undefined,field:string,max:number):string|null{if(value===undefined||value===null)return null;const normalized=String(value).trim();if(!normalized)return null;if(normalized.length>max)throw this.bad(`${field} is too long`,field,'INVALID_SIGNATURE_TEMPLATE_TEXT');return normalized;}
  private optionalEmail(value:string|null|undefined):string|null{const email=this.optionalText(value,'senderEmail',255);if(email!==null&&!EMAIL.test(email))throw this.bad('senderEmail is invalid','senderEmail','INVALID_SIGNATURE_SENDER_EMAIL');return email?.toLowerCase()??null;}
  private routing(value:string):string{if(value!=='parallel'&&value!=='sequential')throw this.bad('routingMode is invalid','routingMode','INVALID_SIGNATURE_ROUTING_MODE');return value;}
  private expiration(value:number):number{if(!Number.isSafeInteger(value)||value<1||value>3650)throw this.bad('expirationDays must be between 1 and 3650','expirationDays','INVALID_SIGNATURE_EXPIRATION');return value;}
  private positiveId(value:number,field:string):number{if(!Number.isSafeInteger(value)||value<1)throw this.bad(`${field} must be positive`,field,'INVALID_SIGNATURE_REFERENCE');return value;}
  private bad(message:string,field:string,reason:string){return itemizeGraphqlError(message,'BAD_USER_INPUT',{field,reason});}
  private writeError(error:unknown):never{if(error instanceof SignatureQuotaExceededError)throw itemizeGraphqlError(error.message,'FORBIDDEN',{reason:'SIGNATURE_MONTHLY_LIMIT'});if(error instanceof SignatureReferenceError)throw itemizeGraphqlError(error.message,'BAD_USER_INPUT',{reason:'INVALID_SIGNATURE_REFERENCE'});throw error;}
}
