import { SignatureTemplatesRepository } from './signature-templates.repository';
import { SignatureTemplatesService } from './signature-templates.service';

const template={id:5,organization_id:3,title:'Agreement',description:null,message:null,has_file:true,file_name:'agreement.pdf',file_type:'application/pdf',file_size:'800',page_count:1,is_ready:true,created_by:4,created_at:new Date('2026-01-01'),updated_at:new Date('2026-01-02')};
describe('SignatureTemplatesService',()=>{
  const repository={hasFeatureAccess:jest.fn(),findAll:jest.fn(),findDetail:jest.fn(),create:jest.fn(),update:jest.fn(),delete:jest.fn(),instantiate:jest.fn()} as unknown as jest.Mocked<SignatureTemplatesRepository>;
  const service=new SignatureTemplatesService(repository);
  beforeEach(()=>{jest.clearAllMocks();repository.hasFeatureAccess.mockResolvedValue(true);});
  it('maps list and tenant-qualified aggregate detail',async()=>{repository.findAll.mockResolvedValue([template]);await expect(service.list(3)).resolves.toEqual([expect.objectContaining({id:5,hasFile:true,fileSize:800})]);repository.findDetail.mockResolvedValue({template,roles:[{id:1,template_id:5,role_name:'Signer',signing_order:1}],fields:[]});await expect(service.detail(3,5)).resolves.toEqual({template:expect.objectContaining({id:5}),roles:[expect.objectContaining({roleName:'Signer'})],fields:[]});});
  it('fails closed on foreign IDs and unavailable plans',async()=>{repository.findDetail.mockResolvedValue(null);await expect(service.detail(3,5)).rejects.toMatchObject({extensions:{code:'NOT_FOUND'}});repository.hasFeatureAccess.mockResolvedValue(false);await expect(service.list(3)).rejects.toMatchObject({extensions:{code:'FORBIDDEN'}});});
  it('normalizes one atomic template definition',async()=>{repository.create.mockResolvedValue({kind:'created',row:template,replayed:false});await expect(service.create(3,4,{title:' Agreement ',roles:[{roleName:'Signer'}],fields:[{roleName:'Signer',fieldType:'signature',pageNumber:1,xPosition:10,yPosition:20,width:30,height:10}]},'template-create-1')).resolves.toMatchObject({id:5});expect(repository.create).toHaveBeenCalledWith(3,4,expect.objectContaining({title:'Agreement',roles:[{roleName:'Signer',signingOrder:1}],fields:[expect.objectContaining({roleName:'Signer',fieldType:'signature'})]}),'template-create-1',expect.stringMatching(/^[a-f0-9]{64}$/));});
  it('rejects duplicate roles and orphaned fields before writes',async()=>{await expect(service.create(3,4,{title:'Agreement',roles:[{roleName:'Signer'},{roleName:' signer '}]},'template-create-2')).rejects.toMatchObject({extensions:{code:'BAD_USER_INPUT',reason:'DUPLICATE_SIGNATURE_TEMPLATE_ROLE'}});await expect(service.create(3,4,{title:'Agreement',roles:[],fields:[{roleName:'Signer',fieldType:'text',pageNumber:1,xPosition:1,yPosition:1,width:10,height:10}]},'template-create-3')).rejects.toMatchObject({extensions:{code:'BAD_USER_INPUT',reason:'INVALID_SIGNATURE_TEMPLATE_FIELD_ROLE'}});expect(repository.create).not.toHaveBeenCalled();});
  it('surfaces conflicting and unavailable template creation receipts',async()=>{repository.create.mockResolvedValueOnce({kind:'idempotency_conflict'}).mockResolvedValueOnce({kind:'result_unavailable'});await expect(service.create(3,4,{title:'Agreement'},'template-create-4')).rejects.toMatchObject({extensions:{code:'CONFLICT',reason:'IDEMPOTENCY_KEY_REUSED'}});await expect(service.create(3,4,{title:'Agreement'},'template-create-5')).rejects.toMatchObject({extensions:{code:'CONFLICT',reason:'IDEMPOTENCY_RESULT_UNAVAILABLE'}});});
});
